config/routes.rb
VarageSale::Application.routes.draw do
  resources :photos
  root :to => 'photos#index'
end

app/models/photo.rb
# encoding: UTF-8
class Photo < ActiveRecord::Base
  attr_accessible :desc, :image, :score, :remote_image_url
  mount_uploader :image, ImageUploader

  scope :young, lambda { where("created_at > ?", Time.zone.now - 7.days ) }
  scope :sorted_young, young.order("score DESC")

  def url
    image.blank? ? nil : image.url
  end

  def age
    Time.now - created_at
  end

  def score_up
    self.score += 1
    self.save
  end

  def young?
    true if age < 7.days
  end

  def old?
    !young?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    @photos = Photo.sorted_young.all
  end
  def update
    @photo = Photo.find(params[:id])
    @photo.score_up
    redirect_to :action => :index
  end
  def new
    @photo = Photo.new
  end
  
  def create
    @photo = Photo.create(params[:photo])
    if @photo.save
      redirect_to action: :index
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/layouts/application.html.slim
doctype html
== "<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->"
== "<!--[if lt IE 7 ]> <html class=\"ie6\" lang=\"en\"> <![endif]-->"
== "<!--[if IE 7 ]>    <html class=\"ie7\" lang=\"en\"> <![endif]-->"
== "<!--[if IE 8 ]>    <html class=\"ie8\" lang=\"en\"> <![endif]-->"
== "<!--[if IE 9 ]>    <html class=\"ie9\" lang=\"en\"> <![endif]-->"
== "<!--[if (gt IE 9)|!(IE)]><!--> <html lang=\"en\"> <!--<![endif]-->"

head
  meta charset="utf-8"

  / Uncomment to make IE8 render like IE7
  / meta http-equiv="X-UA-Compatible" content="IE=7"

  / Set the viewport width to device width for mobile
  meta name="viewport" content="width=device-width, initial-scale=1.0"

  title= content_for?(:title) ? yield(:title) : "Untitled"

  = stylesheet_link_tag "application"
  = javascript_include_tag "vendor/custom.modernizr"
  = csrf_meta_tag

body

  /! Header and Nav
  nav.top-bar
     ul.right
       li
         = link_to "Upload", new_photo_path
  /! End Header and Nav
  /! Main Grid Section
  == yield
  .row
    .large-12.columns
      .panel
        h5 Lost photos ?
        p Previous photos have been lost in time.
  /! End Grid Section
  /! Footer
  footer.row
    .large-12.columns
      hr/
      .row
        .large-6.columns
          p &copy; Copyleft no one at all.
        .large-6.columns
          ul.inline-list.right
            li
              a href="#"
            li
              a href="#"
            li
              a href="#"
            li
              a href="#"


  = javascript_include_tag "application"

app/views/photos/_photo.slim
.large-4.columns
  .panel
    = link_to "+1", {action: :update, id: photo.id}, method: :put
    p
      img width="400" height="300" src="#{photo.url}"
    p
      = photo.desc
      = ", (#{photo.score})"

app/views/photos/index.html.slim
- @photos.each_slice(3) do |row|
  .row
    = render :partial => "photo", :collection => row

app/views/photos/new.html.slim
= form_for @photo do |f|
  .row
    .large-10.columns
      label Desc
      = f.text_field :desc
      br
      label File
      = f.file_field :image
      br
      = f.submit